// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0--rc1
// source: a4/grpc/proto/ricardAlgo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RicardAlgo_Request_FullMethodName = "/ricardAlgo.RicardAlgo/Request"
	RicardAlgo_Reply_FullMethodName   = "/ricardAlgo.RicardAlgo/Reply"
)

// RicardAlgoClient is the client API for RicardAlgo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RicardAlgoClient interface {
	Request(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*ReplyMsg, error)
	Reply(ctx context.Context, in *ReplyMsg, opts ...grpc.CallOption) (*Empty, error)
}

type ricardAlgoClient struct {
	cc grpc.ClientConnInterface
}

func NewRicardAlgoClient(cc grpc.ClientConnInterface) RicardAlgoClient {
	return &ricardAlgoClient{cc}
}

func (c *ricardAlgoClient) Request(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*ReplyMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyMsg)
	err := c.cc.Invoke(ctx, RicardAlgo_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ricardAlgoClient) Reply(ctx context.Context, in *ReplyMsg, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RicardAlgo_Reply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RicardAlgoServer is the server API for RicardAlgo service.
// All implementations must embed UnimplementedRicardAlgoServer
// for forward compatibility.
type RicardAlgoServer interface {
	Request(context.Context, *RequestMsg) (*ReplyMsg, error)
	Reply(context.Context, *ReplyMsg) (*Empty, error)
	mustEmbedUnimplementedRicardAlgoServer()
}

// UnimplementedRicardAlgoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRicardAlgoServer struct{}

func (UnimplementedRicardAlgoServer) Request(context.Context, *RequestMsg) (*ReplyMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedRicardAlgoServer) Reply(context.Context, *ReplyMsg) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reply not implemented")
}
func (UnimplementedRicardAlgoServer) mustEmbedUnimplementedRicardAlgoServer() {}
func (UnimplementedRicardAlgoServer) testEmbeddedByValue()                    {}

// UnsafeRicardAlgoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RicardAlgoServer will
// result in compilation errors.
type UnsafeRicardAlgoServer interface {
	mustEmbedUnimplementedRicardAlgoServer()
}

func RegisterRicardAlgoServer(s grpc.ServiceRegistrar, srv RicardAlgoServer) {
	// If the following call pancis, it indicates UnimplementedRicardAlgoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RicardAlgo_ServiceDesc, srv)
}

func _RicardAlgo_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicardAlgoServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicardAlgo_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicardAlgoServer).Request(ctx, req.(*RequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _RicardAlgo_Reply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicardAlgoServer).Reply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicardAlgo_Reply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicardAlgoServer).Reply(ctx, req.(*ReplyMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// RicardAlgo_ServiceDesc is the grpc.ServiceDesc for RicardAlgo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RicardAlgo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ricardAlgo.RicardAlgo",
	HandlerType: (*RicardAlgoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _RicardAlgo_Request_Handler,
		},
		{
			MethodName: "Reply",
			Handler:    _RicardAlgo_Reply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "a4/grpc/proto/ricardAlgo.proto",
}
