// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: a4/grpc/proto/ricardAlgo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty message
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_a4_grpc_proto_ricardAlgo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_a4_grpc_proto_ricardAlgo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_a4_grpc_proto_ricardAlgo_proto_rawDescGZIP(), []int{0}
}

// Request for critical section
type RequestMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMsg) Reset() {
	*x = RequestMsg{}
	mi := &file_a4_grpc_proto_ricardAlgo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMsg) ProtoMessage() {}

func (x *RequestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_a4_grpc_proto_ricardAlgo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMsg.ProtoReflect.Descriptor instead.
func (*RequestMsg) Descriptor() ([]byte, []int) {
	return file_a4_grpc_proto_ricardAlgo_proto_rawDescGZIP(), []int{1}
}

func (x *RequestMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RequestMsg) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

// Reply granting permission
type ReplyMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMsg) Reset() {
	*x = ReplyMsg{}
	mi := &file_a4_grpc_proto_ricardAlgo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMsg) ProtoMessage() {}

func (x *ReplyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_a4_grpc_proto_ricardAlgo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMsg.ProtoReflect.Descriptor instead.
func (*ReplyMsg) Descriptor() ([]byte, []int) {
	return file_a4_grpc_proto_ricardAlgo_proto_rawDescGZIP(), []int{2}
}

func (x *ReplyMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReplyMsg) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

var File_a4_grpc_proto_ricardAlgo_proto protoreflect.FileDescriptor

const file_a4_grpc_proto_ricardAlgo_proto_rawDesc = "" +
	"\n" +
	"\x1ea4/grpc/proto/ricardAlgo.proto\x12\n" +
	"ricardAlgo\"\a\n" +
	"\x05Empty\"C\n" +
	"\n" +
	"RequestMsg\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId\"A\n" +
	"\bReplyMsg\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId2w\n" +
	"\n" +
	"RicardAlgo\x127\n" +
	"\aRequest\x12\x16.ricardAlgo.RequestMsg\x1a\x14.ricardAlgo.ReplyMsg\x120\n" +
	"\x05Reply\x12\x14.ricardAlgo.ReplyMsg\x1a\x11.ricardAlgo.EmptyB\x0fZ\ra4/grpc/protob\x06proto3"

var (
	file_a4_grpc_proto_ricardAlgo_proto_rawDescOnce sync.Once
	file_a4_grpc_proto_ricardAlgo_proto_rawDescData []byte
)

func file_a4_grpc_proto_ricardAlgo_proto_rawDescGZIP() []byte {
	file_a4_grpc_proto_ricardAlgo_proto_rawDescOnce.Do(func() {
		file_a4_grpc_proto_ricardAlgo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_a4_grpc_proto_ricardAlgo_proto_rawDesc), len(file_a4_grpc_proto_ricardAlgo_proto_rawDesc)))
	})
	return file_a4_grpc_proto_ricardAlgo_proto_rawDescData
}

var file_a4_grpc_proto_ricardAlgo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_a4_grpc_proto_ricardAlgo_proto_goTypes = []any{
	(*Empty)(nil),      // 0: ricardAlgo.Empty
	(*RequestMsg)(nil), // 1: ricardAlgo.RequestMsg
	(*ReplyMsg)(nil),   // 2: ricardAlgo.ReplyMsg
}
var file_a4_grpc_proto_ricardAlgo_proto_depIdxs = []int32{
	1, // 0: ricardAlgo.RicardAlgo.Request:input_type -> ricardAlgo.RequestMsg
	2, // 1: ricardAlgo.RicardAlgo.Reply:input_type -> ricardAlgo.ReplyMsg
	2, // 2: ricardAlgo.RicardAlgo.Request:output_type -> ricardAlgo.ReplyMsg
	0, // 3: ricardAlgo.RicardAlgo.Reply:output_type -> ricardAlgo.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_a4_grpc_proto_ricardAlgo_proto_init() }
func file_a4_grpc_proto_ricardAlgo_proto_init() {
	if File_a4_grpc_proto_ricardAlgo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_a4_grpc_proto_ricardAlgo_proto_rawDesc), len(file_a4_grpc_proto_ricardAlgo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_a4_grpc_proto_ricardAlgo_proto_goTypes,
		DependencyIndexes: file_a4_grpc_proto_ricardAlgo_proto_depIdxs,
		MessageInfos:      file_a4_grpc_proto_ricardAlgo_proto_msgTypes,
	}.Build()
	File_a4_grpc_proto_ricardAlgo_proto = out.File
	file_a4_grpc_proto_ricardAlgo_proto_goTypes = nil
	file_a4_grpc_proto_ricardAlgo_proto_depIdxs = nil
}
